sudo: required
language: bash
services:
  - docker
before_script:
  - docker-compose build app-tree
script: docker-compose run --rm --entrypoint sh -e KBC_DATADIR=/code/tests/data/ app-tree /code/run_tests.sh
after_success:
  - docker images
deploy:
  provider: script
  skip_cleanup: true
  script: ./deploy.sh
  on:
    tags: true
notifications:
  slack:
    slack: keboola:eoqvo0RDzLRDPytuVEHRJNOc
  email: false  
