sudo: required
language: bash
services:
  - docker
before_script:
  - docker-compose build app-tree
script: make testall
after_success:
  - docker images
deploy:
  provider: script
  skip_cleanup: true
  script: ./deploy.sh
  on:
    tags: true
notifications:
  slack:
    slack: keboola:eoqvo0RDzLRDPytuVEHRJNOc
  email: false
