sudo: required
language: bash
services:
  - docker
before_script:
  - docker-compose build r-tree
script: docker-compose run --rm --entrypoint sh -e KBC_DATA_DIR=/code/tests/data/ r-tree /code/run_tests.sh
after_success:
  - docker images
deploy:
  provider: script
  skip_cleanup: true
  script: ./deploy.sh
  on:
    tags: true  
notifications:
  slack: keboola:eoqvo0RDzLRDPytuVEHRJNOc