sudo: required
language: bash
services:
  - docker
before_script:
  - docker-compose build app-tree
script: 
  - docker-compose run --rm --entrypoint=flake8 app-tree
  - docker-compose run --rm --entrypoint=python app-tree -m pytest
after_success:
  - docker images
deploy:
  provider: script
  skip_cleanup: true
  script: ./deploy.sh
  on:
    tags: true
notifications:
  slack:
    slack: keboola:eoqvo0RDzLRDPytuVEHRJNOc
  email: false
