version: '2'
services:
  app:
    build: .
    image: keboola/app-tree
    tty: true
    stdin_open: true
    command: bash
    environment:
      - PYTHONPATH=.
  dev:
    build: .
    image: keboola/app-tree
    tty: true
    stdin_open: true
    command: bash
    volumes:
      - ./:/code
    environment:
      - PYTHONPATH=.
