version: '2'
services:
  app:
    build: .
    image: keboola/app-tree
    tty: true
    stdin_open: true
    command: bash
    environment:
      - PYTHONPATH=.
      - KBC_DATADIR=/data
  dev:
    build: .
    image: keboola/app-tree
    tty: true
    stdin_open: true
    command: sh
    volumes:
      - ./:/code
    environment:
      - PYTHONPATH=.
      - KBC_DATADIR=/data
